import type { DiscoveryRunStats,DestinationForecast,FlightOption,LodgingOption,SurfConditions,SurfDestination,SurfWatch,TripOpportunity } from "@/lib/domain/types";
import type { DiscoveryRepository } from "@/lib/discovery/types";
import { createSupabaseAdminClient } from "./admin";
type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
type WatchRow={id:string;user_id:string;name:string;origin_airport:string;window_days:number;earliest_departure_date:string|null;latest_return_date:string|null;min_trip_nights:number;max_trip_nights:number;max_all_in_cost_per_person:number|string;travelers:number;destination_mode:SurfWatch["destinationMode"];allowed_destination_ids:string[];allowed_regions:string[];skill_level:SurfWatch["skillLevel"];min_surf_score:number;min_wave_height_ft:number|null;max_wave_height_ft:number|null;min_period_seconds:number|null;warm_water_only:boolean;flights_required:boolean;accommodation_required:boolean;board_rental_required:boolean;carry_on_required:boolean;walkable_to_beach_required:boolean;allow_connections:boolean;max_flight_duration_hours:number|null;group_discounts_enabled:boolean;alert_email:string;alerts_enabled:boolean;active:boolean;created_at:string;updated_at:string};
type DestinationRow={id:string;slug:string;name:string;region:string;country:string;latitude:number;longitude:number;nearest_airport_codes:string[];timezone:string;min_skill_level:SurfDestination["minSkillLevel"];max_skill_level:SurfDestination["maxSkillLevel"];preferred_swell_directions:number[];preferred_wind_directions:number[];min_useful_swell_height:number;max_useful_swell_height:number;min_useful_period:number;preferred_tide_range:string|null;typical_board_rental_daily:number|string;typical_local_transport_daily:number|string;beach_walkable_default:boolean;warm_water_months:number[];active:boolean};
type OpportunityRow={id:string;identity_key:string;watch_id:string;user_id:string;destination_id:string;departure_date:string;return_date:string;surf_window_start:string;surf_window_end:string;surf_timezone:string;surf_score:number;surf_confidence:number;flight_price_per_person:number|string;lodging_total:number|string;lodging_per_person:number|string;board_rental_per_person:number|string;transport_per_person:number|string;baggage_per_person:number|string;total_per_person:number|string;total_group_cost:number|string;flight_option_json:Json;lodging_option_json:Json;surf_conditions_json:Json;booking_links_json:Json;opportunity_score:number;price_source:TripOpportunity["priceSource"];first_detected_at:string;last_detected_at:string;lowest_observed_price:number|string;status:TripOpportunity["status"]};
const asNumber=(value:number|string)=>typeof value==="number"?value:Number(value);
function mapWatch(r:WatchRow):SurfWatch{return{id:r.id,userId:r.user_id,name:r.name,originAirport:r.origin_airport,windowDays:r.window_days,earliestDepartureDate:r.earliest_departure_date??undefined,latestReturnDate:r.latest_return_date??undefined,minTripNights:r.min_trip_nights,maxTripNights:r.max_trip_nights,maxAllInCostPerPerson:asNumber(r.max_all_in_cost_per_person),travelers:r.travelers,destinationMode:r.destination_mode,allowedDestinationIds:r.allowed_destination_ids,allowedRegions:r.allowed_regions,skillLevel:r.skill_level,minSurfScore:r.min_surf_score,minWaveHeightFt:r.min_wave_height_ft??undefined,maxWaveHeightFt:r.max_wave_height_ft??undefined,minPeriodSeconds:r.min_period_seconds??undefined,warmWaterOnly:r.warm_water_only,flightsRequired:r.flights_required,accommodationRequired:r.accommodation_required,boardRentalRequired:r.board_rental_required,carryOnRequired:r.carry_on_required,walkableToBeachRequired:r.walkable_to_beach_required,allowConnections:r.allow_connections,maxFlightDurationHours:r.max_flight_duration_hours??undefined,groupDiscountsEnabled:r.group_discounts_enabled,alertEmail:r.alert_email,alertsEnabled:r.alerts_enabled,active:r.active,createdAt:r.created_at,updatedAt:r.updated_at};}
function parseNumericRange(value:string|null):[number,number]|undefined{if(!value||value.length<5)return;const[minRaw,maxRaw]=value.slice(1,-1).split(",",2),min=Number(minRaw),max=Number(maxRaw);return Number.isFinite(min)&&Number.isFinite(max)?[min,max]:undefined;}
function mapDestination(r:DestinationRow):SurfDestination{return{id:r.id,slug:r.slug,name:r.name,region:r.region,country:r.country,latitude:r.latitude,longitude:r.longitude,nearestAirportCodes:r.nearest_airport_codes,timezone:r.timezone,minSkillLevel:r.min_skill_level,maxSkillLevel:r.max_skill_level,preferredSwellDirections:r.preferred_swell_directions,preferredWindDirections:r.preferred_wind_directions,minUsefulSwellHeight:r.min_useful_swell_height,maxUsefulSwellHeight:r.max_useful_swell_height,minUsefulPeriod:r.min_useful_period,preferredTideRange:parseNumericRange(r.preferred_tide_range),typicalBoardRentalDaily:asNumber(r.typical_board_rental_daily),typicalLocalTransportDaily:asNumber(r.typical_local_transport_daily),beachWalkableDefault:r.beach_walkable_default,warmWaterMonths:r.warm_water_months,active:r.active};}
function mapOpportunity(r:OpportunityRow):TripOpportunity{return{id:r.id,identityKey:r.identity_key,watchId:r.watch_id,userId:r.user_id,destinationId:r.destination_id,departureDate:r.departure_date,returnDate:r.return_date,surfWindowStart:r.surf_window_start,surfWindowEnd:r.surf_window_end,surfTimezone:r.surf_timezone,surfScore:r.surf_score,surfConfidence:r.surf_confidence,flightPricePerPerson:asNumber(r.flight_price_per_person),lodgingTotal:asNumber(r.lodging_total),lodgingPerPerson:asNumber(r.lodging_per_person),boardRentalPerPerson:asNumber(r.board_rental_per_person),transportPerPerson:asNumber(r.transport_per_person),baggagePerPerson:asNumber(r.baggage_per_person),totalPerPerson:asNumber(r.total_per_person),totalGroupCost:asNumber(r.total_group_cost),flightOption:r.flight_option_json as unknown as FlightOption,lodgingOption:r.lodging_option_json as unknown as LodgingOption,surfConditions:r.surf_conditions_json as unknown as SurfConditions,bookingLinks:r.booking_links_json as Record<string,string|undefined>,opportunityScore:r.opportunity_score,priceSource:r.price_source,firstDetectedAt:r.first_detected_at,lastDetectedAt:r.last_detected_at,lowestObservedPrice:asNumber(r.lowest_observed_price),status:r.status};}

export class SupabaseDiscoveryRepository implements DiscoveryRepository {
  private get client(){const client=createSupabaseAdminClient();if(!client)throw new Error("Supabase service-role credentials are not configured");return client;}
  async saveForecast(destination:SurfDestination,forecast:DestinationForecast){const{error}=await this.client.from("surf_forecast_snapshots").insert({destination_id:destination.id,provider:forecast.provider,fetched_at:forecast.fetchedAt,forecast_start:forecast.hours.at(0)?.time??null,forecast_end:forecast.hours.at(-1)?.time??null,forecast_timezone:forecast.timezone,payload:forecast as unknown as Json});if(error)throw error;}
  async listActiveWatches(){const{data,error}=await this.client.from("surf_watches").select("*").eq("active",true);if(error)throw error;return(data as WatchRow[]).map(mapWatch);}
  async listActiveDestinations(){const{data,error}=await this.client.from("surf_destinations").select("*").eq("active",true);if(error)throw error;return(data as DestinationRow[]).map(mapDestination);}
  async expirePastOpportunities(today:string){const{data,error}=await this.client.from("trip_opportunities").update({status:"expired",updated_at:new Date().toISOString()}).eq("status","active").lt("return_date",today).select("id");if(error)throw error;return data?.length??0;}
  async startRun(){const{data,error}=await this.client.from("discovery_runs").insert({status:"running"}).select("id").single();if(error)throw error;return data.id as string;}
  async finishRun(runId:string,status:"completed"|"partial"|"failed",stats:DiscoveryRunStats){const{error}=await this.client.from("discovery_runs").update({completed_at:new Date().toISOString(),status,watch_count:stats.watchCount,destinations_scanned:stats.destinationsScanned,surf_candidates:stats.surfCandidates,travel_searches:stats.travelSearches,opportunities_found:stats.opportunitiesFound,alerts_sent:stats.alertsSent,error_count:stats.errorCount}).eq("id",runId);if(error)throw error;}
  async getPrevious(identityKey:string){const{data,error}=await this.client.from("trip_opportunities").select("*").eq("identity_key",identityKey).maybeSingle();if(error)throw error;return data?mapOpportunity(data as OpportunityRow):null;}
  async saveOpportunity(opportunity:TripOpportunity){const previous=await this.getPrevious(opportunity.identityKey),now=new Date().toISOString(),payload={identity_key:opportunity.identityKey,watch_id:opportunity.watchId,user_id:opportunity.userId,destination_id:opportunity.destinationId,departure_date:opportunity.departureDate,return_date:opportunity.returnDate,surf_window_start:opportunity.surfWindowStart,surf_window_end:opportunity.surfWindowEnd,surf_timezone:opportunity.surfTimezone,surf_score:opportunity.surfScore,surf_confidence:opportunity.surfConfidence,flight_price_per_person:opportunity.flightPricePerPerson,lodging_total:opportunity.lodgingTotal,lodging_per_person:opportunity.lodgingPerPerson,board_rental_per_person:opportunity.boardRentalPerPerson,transport_per_person:opportunity.transportPerPerson,baggage_per_person:opportunity.baggagePerPerson,total_per_person:opportunity.totalPerPerson,total_group_cost:opportunity.totalGroupCost,flight_option_json:opportunity.flightOption as unknown as Json,lodging_option_json:opportunity.lodgingOption as unknown as Json,surf_conditions_json:opportunity.surfConditions as unknown as Json,booking_links_json:opportunity.bookingLinks as unknown as Json,opportunity_score:opportunity.opportunityScore,price_source:opportunity.priceSource,first_detected_at:previous?.firstDetectedAt??now,last_detected_at:now,lowest_observed_price:Math.min(previous?.lowestObservedPrice??Number.POSITIVE_INFINITY,opportunity.totalPerPerson),status:previous?.status==="booked"||previous?.status==="dismissed"?previous.status:opportunity.status,updated_at:now};const{data,error}=await this.client.from("trip_opportunities").upsert(payload,{onConflict:"identity_key"}).select("*").single();if(error)throw error;return mapOpportunity(data as OpportunityRow);}
  async hasSentAlert(opportunityId:string){const{count,error}=await this.client.from("alerts").select("id",{count:"exact",head:true}).eq("opportunity_id",opportunityId).eq("status","sent");if(error)throw error;return(count??0)>0;}
  async saveAlert(input:{watch:SurfWatch;opportunity:TripOpportunity;status:"sent"|"failed"|"skipped";reasons:string[];providerMessageId?:string;errorMessage?:string}){if(!input.opportunity.id)throw new Error("Cannot persist alert for unsaved opportunity");const{error}=await this.client.from("alerts").insert({user_id:input.watch.userId,watch_id:input.watch.id,opportunity_id:input.opportunity.id,type:"opportunity",status:input.status,reasons:input.reasons,sent_at:input.status==="sent"?new Date().toISOString():null,provider_message_id:input.providerMessageId??null,error_message:input.errorMessage??null});if(error)throw error;}
  async saveSnapshot(opportunity:TripOpportunity){if(!opportunity.id)throw new Error("Cannot snapshot an unsaved opportunity");const{error}=await this.client.from("opportunity_snapshots").insert({opportunity_id:opportunity.id,flight_price:opportunity.flightPricePerPerson,lodging_price:opportunity.lodgingTotal,all_in_price:opportunity.totalPerPerson,surf_score:opportunity.surfScore});if(error)throw error;}
}
