"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import styles from "./BookDiscovery.module.css";

type Book = { id:string; title:string; author:string; year:number; pages:number; cover:string; hook:string; description:string; tags:string[]; energy:"quiet"|"medium"|"high"; length:"short"|"medium"|"long" };
type Taste = Record<string,number>;

const BOOKS:Book[]=[
{id:"piranesi",title:"Piranesi",author:"Susanna Clarke",year:2020,pages:245,cover:"https://covers.openlibrary.org/b/isbn/9781635575637-L.jpg",hook:"A beautiful impossible house. One man mapping it. Something is very wrong.",description:"Dreamlike, compact and strange without being difficult. It rewards going in with almost no context.",tags:["weird","literary","mystery","atmospheric","fast"],energy:"medium",length:"short"},
{id:"shantaram",title:"Shantaram",author:"Gregory David Roberts",year:2003,pages:936,cover:"https://covers.openlibrary.org/b/isbn/9780312330538-L.jpg",hook:"An escaped convict disappears into Bombay and builds an entirely new life.",description:"Huge, immersive, messy and addictive. The kind of book you live inside for a while.",tags:["adventure","travel","crime","immersive","epic"],energy:"high",length:"long"},
{id:"east-of-eden",title:"East of Eden",author:"John Steinbeck",year:1952,pages:601,cover:"https://covers.openlibrary.org/b/isbn/9780142004234-L.jpg",hook:"Two families, one valley, and generations of people trying to choose who they become.",description:"A classic that reads far more immediately than its reputation suggests. Big emotions, sharp characters, enormous payoff.",tags:["classic","literary","family","epic","character"],energy:"medium",length:"long"},
{id:"into-thin-air",title:"Into Thin Air",author:"Jon Krakauer",year:1997,pages:368,cover:"https://covers.openlibrary.org/b/isbn/9780385494786-L.jpg",hook:"A first-hand account of the 1996 Everest disaster from a writer who was actually on the mountain.",description:"Extremely readable nonfiction with real stakes. It moves like a thriller because the events themselves were one.",tags:["nonfiction","adventure","survival","fast","true"],energy:"high",length:"medium"},
{id:"three-body",title:"The Three-Body Problem",author:"Cixin Liu",year:2008,pages:400,cover:"https://covers.openlibrary.org/b/isbn/9780765382030-L.jpg",hook:"Humanity discovers it may not be alone, and that someone on Earth has already answered back.",description:"Idea-dense science fiction built around escalating discoveries rather than conventional space-opera action.",tags:["sci-fi","ideas","mystery","big-concept","weird"],energy:"medium",length:"medium"},
{id:"shoe-dog",title:"Shoe Dog",author:"Phil Knight",year:2016,pages:400,cover:"https://covers.openlibrary.org/b/isbn/9781501135927-L.jpg",hook:"Nike before Nike was Nike: debt, bad decisions, obsession and a tiny group trying to survive.",description:"A founder memoir that feels unusually candid and operational rather than polished into business mythology.",tags:["business","memoir","entrepreneurship","fast","true"],energy:"high",length:"medium"},
{id:"stasi",title:"Stasiland",author:"Anna Funder",year:2002,pages:304,cover:"https://covers.openlibrary.org/b/isbn/9780062077325-L.jpg",hook:"Ordinary people tell what it was like to live under East Germany's surveillance state.",description:"History through intimate stories rather than a textbook lens. Weird, human and often darkly funny.",tags:["history","nonfiction","politics","true","human"],energy:"medium",length:"medium"},
{id:"barbarian-days",title:"Barbarian Days",author:"William Finnegan",year:2015,pages:512,cover:"https://covers.openlibrary.org/b/isbn/9780143109396-L.jpg",hook:"A lifetime organized around waves, places, obsession and the question of why anyone keeps surfing.",description:"The definitive literary surf memoir: travel, risk, aging and wave knowledge without romanticizing the culture.",tags:["surf","memoir","travel","literary","true"],energy:"medium",length:"long"},
{id:"the-road",title:"The Road",author:"Cormac McCarthy",year:2006,pages:287,cover:"https://covers.openlibrary.org/b/isbn/9780307387899-L.jpg",hook:"A father and son walk through the remains of America carrying almost nothing but each other.",description:"Bleak, spare and emotionally direct. Short chapters make it move faster than its subject matter suggests.",tags:["literary","dark","post-apocalyptic","fast","emotional"],energy:"medium",length:"short"},
{id:"project-hail-mary",title:"Project Hail Mary",author:"Andy Weir",year:2021,pages:496,cover:"https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",hook:"A man wakes up alone on a spacecraft and gradually realizes why he was sent there.",description:"Problem-solving science fiction with constant forward motion and an unusually likable central relationship.",tags:["sci-fi","adventure","fast","fun","big-concept"],energy:"high",length:"long"},
{id:"wind-up-bird",title:"The Wind-Up Bird Chronicle",author:"Haruki Murakami",year:1994,pages:607,cover:"https://covers.openlibrary.org/b/isbn/9780679775430-L.jpg",hook:"A missing cat turns into a missing wife, a dry well, strange neighbors and reality quietly coming apart.",description:"Long, surreal and hypnotic. Best when you want atmosphere and discovery more than a tidy plot machine.",tags:["weird","literary","surreal","atmospheric","mystery"],energy:"quiet",length:"long"},
{id:"anthropocene",title:"The Anthropocene Reviewed",author:"John Green",year:2021,pages:293,cover:"https://covers.openlibrary.org/b/isbn/9780525555216-L.jpg",hook:"Human life reviewed on a five-star scale: Diet Dr Pepper, sunsets, plague, scratch-and-sniff stickers.",description:"Funny, thoughtful essays you can read individually or straight through. Good when a novel feels like too much commitment.",tags:["essays","nonfiction","funny","thoughtful","short"],energy:"quiet",length:"short"},
{id:"open",title:"Open",author:"Andre Agassi",year:2009,pages:400,cover:"https://covers.openlibrary.org/b/isbn/9780307388407-L.jpg",hook:"One of the world's best tennis players begins his memoir by telling you he hates tennis.",description:"An unusually vulnerable sports memoir about talent, identity, competition and the cost of being exceptional at something you did not choose.",tags:["memoir","sports","true","fast","human"],energy:"high",length:"medium"},
{id:"endurance",title:"Endurance",author:"Alfred Lansing",year:1959,pages:282,cover:"https://covers.openlibrary.org/b/isbn/9780465062881-L.jpg",hook:"Shackleton's ship is crushed by Antarctic ice. Getting home becomes the entire story.",description:"Lean survival nonfiction with almost no wasted motion. A century-old expedition that still reads like an impossible sequence of escalating problems.",tags:["nonfiction","adventure","survival","true","fast"],energy:"high",length:"short"},
{id:"kitchen-confidential",title:"Kitchen Confidential",author:"Anthony Bourdain",year:2000,pages:312,cover:"https://covers.openlibrary.org/b/isbn/9780060899226-L.jpg",hook:"Restaurants from the other side of the swinging kitchen door: ego, craft, drugs, disasters and people who love the work anyway.",description:"Fast, funny and opinionated. Bourdain's voice is the product as much as the restaurant stories are.",tags:["memoir","food","travel","funny","fast"],energy:"high",length:"medium"},
{id:"never-let-me-go",title:"Never Let Me Go",author:"Kazuo Ishiguro",year:2005,pages:288,cover:"https://covers.openlibrary.org/b/isbn/9781400078776-L.jpg",hook:"Three friends grow up at an English boarding school where something about their future is being carefully withheld.",description:"Quiet speculative fiction that reveals its premise gently and then makes it emotionally unavoidable.",tags:["literary","sci-fi","quiet","emotional","mystery"],energy:"quiet",length:"short"},
{id:"bad-blood",title:"Bad Blood",author:"John Carreyrou",year:2018,pages:352,cover:"https://covers.openlibrary.org/b/isbn/9781524731656-L.jpg",hook:"Theranos promised to reinvent blood testing. Almost none of it worked.",description:"Investigative business nonfiction that reads like a corporate thriller and is especially good on how intelligent people rationalize obvious warning signs.",tags:["business","nonfiction","true","fast","crime"],energy:"high",length:"medium"},
{id:"snow-crash",title:"Snow Crash",author:"Neal Stephenson",year:1992,pages:480,cover:"https://covers.openlibrary.org/b/isbn/9780553380958-L.jpg",hook:"A hacker and pizza-delivery swordsman gets pulled into a virus spreading through both computers and human minds.",description:"Hyperactive cyberpunk full of ideas, satire and ridiculous velocity. Best if you want inventive rather than restrained.",tags:["sci-fi","weird","fast","fun","big-concept"],energy:"high",length:"long"}
];

const VIBES=["surprise me","fast","weird","adventure","literary","nonfiction","sci-fi","business","surf","dark"];
const load=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}};

export default function BookDiscovery(){
 const [vibe,setVibe]=useState("surprise me"); const [index,setIndex]=useState(0); const [saved,setSaved]=useState<string[]>([]); const [rejected,setRejected]=useState<string[]>([]); const [seen,setSeen]=useState<string[]>([]); const [taste,setTaste]=useState<Taste>({}); const [showShelf,setShowShelf]=useState(false); const [ready,setReady]=useState(false);
 useEffect(()=>{setSaved(load("booksurf-shelf",[]));setRejected(load("booksurf-rejected",[]));setSeen(load("booksurf-seen",[]));setTaste(load("booksurf-taste",{}));setReady(true)},[]);
 const score=(b:Book)=>b.tags.reduce((sum,t)=>sum+(taste[t]||0),0)+(taste[`energy:${b.energy}`]||0)+(taste[`length:${b.length}`]||0)+(seen.includes(b.id)?-8:0);
 const pool=useMemo(()=>BOOKS.filter(b=>!rejected.includes(b.id)).filter(b=>vibe==="surprise me"||b.tags.includes(vibe)).sort((a,b)=>score(b)-score(a)),[vibe,rejected,seen,taste]);
 const fallback=BOOKS.filter(b=>!rejected.includes(b.id)).sort((a,b)=>score(b)-score(a)); const candidates=pool.length?pool:fallback; const book=candidates[index%Math.max(candidates.length,1)]||BOOKS[0]; const shelf=BOOKS.filter(b=>saved.includes(b.id));
 const persist=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value));
 const learn=(b:Book,amount:number)=>{const n={...taste};[...b.tags,`energy:${b.energy}`,`length:${b.length}`].forEach(t=>n[t]=(n[t]||0)+amount);setTaste(n);persist("booksurf-taste",n)};
 const markSeen=(id:string)=>{if(seen.includes(id))return;const n=[...seen,id];setSeen(n);persist("booksurf-seen",n)};
 const next=()=>{markSeen(book.id);setIndex(i=>i+1)}; const changeVibe=(v:string)=>{setVibe(v);setIndex(0)};
 const save=()=>{markSeen(book.id);learn(book,3);const n=saved.includes(book.id)?saved:[...saved,book.id];setSaved(n);persist("booksurf-shelf",n);setIndex(i=>i+1)};
 const skip=()=>{markSeen(book.id);learn(book,-2);const n=rejected.includes(book.id)?rejected:[...rejected,book.id];setRejected(n);persist("booksurf-rejected",n);setIndex(0)};
 const remove=(id:string)=>{const n=saved.filter(x=>x!==id);setSaved(n);persist("booksurf-shelf",n)};
 const reset=()=>{["booksurf-shelf","booksurf-rejected","booksurf-seen","booksurf-taste"].forEach(k=>localStorage.removeItem(k));setSaved([]);setRejected([]);setSeen([]);setTaste({});setIndex(0)};
 const tasteTags=Object.entries(taste).filter(([k,v])=>!k.includes(":")&&v>0).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k])=>k);
 if(!ready)return <main className={styles.shell}/>;
 return <main className={styles.shell}>
  <header className={styles.header}><Link href="/" className={styles.brand}><strong>BOOKSURF</strong><span>Surf books</span></Link><button className={styles.shelfButton} onClick={()=>setShowShelf(v=>!v)}>Shelf <span>{saved.length}</span></button></header>
  <section className={styles.hero}><div className={styles.kicker}>Don’t search. Surf.</div><h1>Find the book<br/>you actually want<br/>to start tonight.</h1><p>Tell us with your thumb, not a questionnaire. Keep what catches you. Kill what doesn’t. The wave gets better as you surf.</p></section>
  <nav className={styles.vibes} aria-label="Book vibes">{VIBES.map(v=><button key={v} className={v===vibe?styles.activeVibe:""} onClick={()=>changeVibe(v)}>{v}</button>)}</nav>
  {tasteTags.length>0&&<div className={styles.tasteLine}><strong>Your current taste:</strong> {tasteTags.map(t=>`#${t}`).join("  ")} <button onClick={reset}>reset</button></div>}
  <section className={styles.stage}><div className={styles.coverWrap}><div className={styles.coverShadow}/><img className={styles.cover} src={book.cover} alt={`${book.title} cover`}/><div className={styles.counter}>{seen.length} surfed</div></div>
   <article className={styles.bookInfo}><div className={styles.meta}>{book.year} · {book.pages} pages · {book.length} · {book.energy} energy</div><h2>{book.title}</h2><div className={styles.author}>by {book.author}</div><p className={styles.hook}>{book.hook}</p><p className={styles.description}>{book.description}</p><div className={styles.tags}>{book.tags.slice(0,5).map(tag=><button key={tag} onClick={()=>changeVibe(tag)}>#{tag}</button>)}</div>
    <div className={styles.actions}><button className={styles.keep} onClick={save}>Keep this</button><button className={styles.next} onClick={next}>Next →</button><button className={styles.nope} onClick={skip}>Not for me</button></div>
    <div className={styles.buyRow}><a href={`https://openlibrary.org/search?q=${encodeURIComponent(`${book.title} ${book.author}`)}`} target="_blank" rel="noreferrer">Find the book ↗</a><span>{saved.includes(book.id)?"On your shelf":"Your choices tune the next pick"}</span></div>
   </article></section>
  <section className={styles.promise}><div><span>01</span><strong>It learns from behavior</strong><p>A keep strongly raises related tastes. A rejection pushes those signals down. A simple next is only a weak signal.</p></div><div><span>02</span><strong>Novelty stays in the mix</strong><p>Books you have already surfed fall behind unseen books, so personalization does not become repetition.</p></div><div><span>03</span><strong>Your shelf becomes taste</strong><p>The useful asset is not a list of books. It is an evolving model of what actually makes you want to read.</p></div></section>
  {showShelf&&<aside className={styles.shelf}><div className={styles.shelfHeader}><div><div className={styles.kicker}>Your shelf</div><h3>Books worth coming back to</h3></div><button onClick={()=>setShowShelf(false)}>×</button></div>{shelf.length===0?<p className={styles.empty}>Nothing saved yet. Keep a book when one catches you.</p>:<div className={styles.shelfGrid}>{shelf.map(b=><div className={styles.shelfItem} key={b.id}><img src={b.cover} alt=""/><div><strong>{b.title}</strong><span>{b.author}</span><button onClick={()=>remove(b.id)}>Remove</button></div></div>)}</div>}</aside>}
 </main>;
}
